title: WANG BEIYI's Homepage ğŸ¯âœ¨
name: WANG BEIYI

# ç½‘ç«™ç®€ä»‹
description: "åŒ—æµ·é“å¤§å­¦ã®ç•™å­¦ç”Ÿ<br>ãƒˆãƒ©ğŸ¯ã®ã‚ˆã†ã«å‹‡å¾€é‚é€²ï¼"

url: https://mia1017.github.io
baseurl: ""

# ä¸»é¢˜
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# ä½œè€…ä¿¡æ¯ï¼ˆå¤´åƒåç‰‡ï¼‰
author:
  name: WANG BEIYI
  avatar: /image/IMG_7793.JPG
  bio: |
    åŒ—æµ·é“å¤§å­¦ã®ç•™å­¦ç”Ÿ<br>ãƒˆãƒ©ğŸ¯ã®ã‚ˆã†ã«å‹‡å¾€é‚é€²ï¼  

    ğŸ¨ [è¶£å‘³](#hobby)  
    ğŸ“š [ç ”ç©¶ãƒ†ãƒ¼ãƒï¼†èˆˆå‘³åˆ†é‡](#research)  
    ğŸ“© [é€£çµ¡å…ˆ](#contact)
  location: 
  links: []   

# é…è‰²çš®è‚¤
minimal_mistakes_skin: "default"
