theme: jekyll-theme-slate
title: WANG BEIYI's Homepage ğŸ¯âœ¨
description: Welcome! ãƒ‘ãƒ³ãƒ€ã®åŒéƒ·ã€åŒ—æµ·é“å¤§å­¦ã®ç•™å­¦ç”Ÿã§ã™
plugins:
  - jemoji
url: "https://Mia1017.github.io/"
markdown: kramdown
